"""
email_sender.py — Send a patient Q&A conversation summary via Gmail SMTP.

Required secrets / env vars:
    EMAIL_SENDER      your Gmail address        e.g. you@gmail.com
    EMAIL_PASSWORD    Gmail App Password        16-char code from Google account
    EMAIL_RECIPIENT   fallback recipient        used if no address given in chat
"""

import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime


def get_secret(key):
    """Read from Streamlit secrets when deployed, env var when running locally."""
    try:
        import streamlit as st
        try:
            return st.secrets.get(key)
        except Exception:
            pass
    except ImportError:
        pass
    return os.environ.get(key)


def send_summary_email(patient_name, summary_text, recipient_override=None):
    """
    Send a plain-text email with the conversation summary.

    recipient_override: email address typed by the user in chat.
                        Falls back to EMAIL_RECIPIENT secret if not provided.

    Returns (success: bool, message: str)
    """
    sender    = get_secret("EMAIL_SENDER")
    password  = get_secret("EMAIL_PASSWORD")
    recipient = recipient_override or get_secret("EMAIL_RECIPIENT")

    if not sender or not password:
        return False, "Missing EMAIL_SENDER or EMAIL_PASSWORD in secrets."
    if not recipient:
        return False, "No recipient address found. Type 'send summary to you@email.com'."

    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    subject   = f"Patient Q&A Summary — {patient_name} ({timestamp})"

    body = f"""Patient Q&A Conversation Summary
Generated: {timestamp}
Patient:   {patient_name}

{summary_text}

---
This summary was generated by the FHIR Patient Q&A POC chatbot.
Data is synthetic — not a real patient record.
"""

    msg = MIMEMultipart()
    msg["From"]    = sender
    msg["To"]      = recipient
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            server.sendmail(sender, recipient, msg.as_string())
        return True, f"Email sent to {recipient}"
    except smtplib.SMTPAuthenticationError:
        return False, "Gmail authentication failed — check your App Password."
    except smtplib.SMTPException as e:
        return False, f"SMTP error: {e}"
    except Exception as e:
        return False, f"Unexpected error: {e}"